apiVersion: v1
kind: Service
metadata:
  name: nuxt-app-service
spec:
  selector:
    app: nuxt-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP